version: '2.0'
services: 
    web:
        image: supakorn19934/nginx-sticky
        container_name: myhr-nginx
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/nginx/html/:/etc/nginx/html/:ro
            - /etc/nginx/ssl/:/etc/nginx/ssl/:ro
            - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - /etc/nginx/log/:/var/log/nginx/:rw